server {
    server_name ringochvinn.46hudik.se;

    root /var/www/ring-och-vinn/site;
    index index.html;

    location /voice/start {
        proxy_pass http://127.0.0.1:8117;
    }

    location /api/ {
        proxy_pass http://127.0.0.1:8117;
        proxy_set_header Host $host;
    }

    location /ws {
        proxy_pass http://127.0.0.1:8115;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_read_timeout 86400;
    }

    location / {
        try_files $uri $uri/ =404;
    }

    listen 80;
}
